name: Build docker image
on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/docker.yml
      - Dockerfile.compose
      - Dockerfile
  push:
    paths:
      - .github/workflows/docker.yml
      - Dockerfile.compose
      - Dockerfile

env:
  TRITON_CONTAINER_VERSION: 21.12
jobs:
  docker:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch triton-inference-server
        run: git clone --depth 1 https://github.com/triton-inference-server/server triton-inference-server

      - name: Generate Dockerfile
        shell: bash
        run: |
          python3 triton-inference-server/compose.py --dry-run \
            --container-version $TRITON_CONTAINER_VERSION \
            --enable-gpu \
            --backend tensorrt

      - name: Compare repository Dockerfile.compose with generated version
        run: git diff --exit-code

      - name: Build custom triton base image
        shell: bash
        run: |
          cp Dockerfile.compose triton-inference-server/
          cd triton-inference-server/
          docker build -t tritonserver-custom -f Dockerfile.compose .

      - name: Build final triton image
        shell: bash
        run: |
          mkdir server/plugins  # Missing in CI
          docker build -t tritonserver:TRITON_CONTAINER_VERSION -f Dockerfile .

      - name: List images
        run: docker images
